---
title: "for_loop_and_more"
author: "sn0wfree"
date: "11/24/2016"
output:
  word_document:
    toc: yes
  pdf_document:
    latex_engine: xelatex
    number_sections: yes
    toc: yes
---
# Quantitative Research Methods Term 1

this chapter aim at the for loop for r language.

**if you totally understand the for loop from ang another language, you may ignore this chapter**


## for loop
```{r forloop}
for (i in 1:10){print(c(i,i^.5))}
x=0
for (i in 1:10){x[i]=i^.5}
y=0
for (i in 10:2){x[i]=i^.5 
print(x[i])}
#for loop to add each previous number
#function#1
for(i in 1:10){x=x+i 
print(x)}
#function#2
for(i in 1:10){y[i+1]=y[i]+i;print (y[i+1])}
```


## random number
sample the random based on different  distributions
```{r random number}
#uniform to sample data
runif(10,1,10)
#interge digital
trunc(runif(5,1,7))
round(runif(5,1,7),2)
signif(10)

#normally sample
rnorm(5,mean =0 ,sd =1 )
round(rnorm(5,mean =0 ,sd =1 ),2)
for(i in 1:10){print(rnorm(5,-2,3))}
#take sample
sample(x=1:10,replace=TRUE)
sample(x=1:10,size=2,replace=TRUE)
sample(x=1:10,size=1,replace=0)
x=rnorm(10,-.5,2)
t.test(x,mu=0,alternative = "less")
```

## bootstrap-1
```{r bootstrap-1}
x=rnorm(20,-.5,1)
y=sample(1:20,replace = 1)

leaveit=x
mean(leaveit)
m=0
#for(i in 1:10000){print(mean(leaveit[sample(1:20,replace = 1)]))}
for(i in 1:10000){m[i]=mean(leaveit[sample(1:20,replace = 1)])}
mean(m)
sd(m)
t.test(m,mu=-0.5)
boxplot(m)
qqnorm(m)
```
## bootstrap-2
```{r bootstrap-2}

for(i in 1:10000){
  m[i]=mean(leaveit[sample(1:20,replace = 1)])}
pos=0

for (i in 1:10000){
  if (m[i] > 0){
    pos=pos+1
  }
}
pos
```
```{r 2}
leaveit[21]=10
for(i in 1:10000){
  m[i]=mean(leaveit[sample(1:21,replace = 1)])}
pos=0
boxplot(m)
for (i in 1:10000){
  if (m[i] > 0){
    pos=pos+1
  }
}
pos
```

