---
title: "Quantitative Research Methods: history 2 "
author: "sn0wfree"
date: "11/12/2016"
output: 
  pdf_document: 
    number_sections: yes
    toc: yes
---

#history 2 for QRM
##import data and see the first 6 rows data
```{r dataset}

# using Wages.xls
```

##import data
1st step importing from xls or use copy function
```{r import_data}
#bug=read.table("clipboard",header=TRUE)<---this is for windows
#bug=read.table(pipe("pbpaste"),header=TRUE)#<- this is for macos
bug=read.csv("/Users/sn0wfree/Dropbox/PhD(1st)/BST 215Quantitative Research Methods term 1/r code/Wages.csv",header=TRUE)
```

##watch part of data
```{r watch part of data}
head(bug)#<- watch top 6 rows
str(bug)#<- see the data frame for each variables
colnames(bug)#<- show the name of columns:which means show the labels or variables name
```

##attach?
```{r attach}
attach(bug)
```



##plot graph
###plot graph 1:Age-Wage|Gender
```{r plot graph1:Gender}
plot(c(14,66),c(0,12),main="Gender Dis", xlab="Age (years)",ylab="Wage (unknown units)")
points(lowess(Age[Gender=="Female"],Wage[Gender=="Female"]))
points(lowess(Age[Gender=="Male"],Wage[Gender=="Male"]),pch=19)
text(40,6,"Female")
```

###plot graph 2:Age-Wage|Union
```{r plot graph2:Union}
plot(c(14,66),c(0,12),main="Gender Dis", xlab="Age (years)",ylab="Wage (unknown units)")
points(lowess(Age[Union=="Union"],Wage[Union=="Union"]))
points(lowess(Age[Union=="Non_Union"],Wage[Union=="Non_Union"]),pch=19)
text(40,6,"Female")
```


###plot graph 3:Age-Wage|Married

```{r plot graph3:Married}
#Married="Married"
plot(c(14,66),c(0,12),main="Gender Dis", xlab="Age (years)",ylab="Wage (unknown units)")
points(lowess(Age[Gender=="Female" & Married=="Unmarried"],Wage[Gender=="Female" & Married=="Unmarried"]))
points(lowess(Age[Gender=="Male" & Married=="Unmarried"],Wage[Gender=="Male" & Married=="Unmarried"]),pch=19)
text(40,6,"Female")

```

##show information of Occupation
```{r info.Occupation}
table(Occupation)
```


###plot graph 4:Age-Wage|Married

```{r plot graph4:Occupation}
#Occupation=="Management"
plot(c(14,66),c(0,20),main="Gender Dis", xlab="Age (years)",ylab="Wage (unknown units)")
points(lowess(Age[Gender=="Female" & Occupation=="Management"],Wage[Gender=="Female" & Occupation=="Management"]))
points(lowess(Age[Gender=="Male" & Occupation=="Management"],Wage[Gender=="Male" & Occupation=="Management"]),pch=19)
text(40,6,"Female")

```


##plot qqnorm
```{r plot graph:qqnorm}
qqnorm(Wage)
qqnorm(Age)

```



